apiVersion: v1
kind: CronJob
metadata:
  name: CloseAuctions
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: CloseAuctions
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - java CloseAuctions
          restartPolicy: OnFailure